# -------------------
# Jekyll Config
# --------------------
baseurl: ""
url: "https://www.thijspeirelinck.be"
permalink: pretty
markdown: kramdown
highlighter: rouge
collections_dir: collections

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-paginate-v2
  - jekyll-sitemap


# paginate: 6
# paginate_path: "/hikes/page/:num"

# Pagination Settings
pagination:
  enabled: true
  per_page: 8
  permalink: '/page/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

collections:
  projects:
    output: true
    permalink: /photography/:path/
  hikes:
    output: true
    permalink: /hikes/:path/
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: hikes
    values:
      layout: project
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      weight: 999
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      permalink: /category/:basename/
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

# storage
# bucketurl: "/assets/images/content"
# absbucketurl: "https://www.thijspeirelinck.be"
bucketurl: "https://f003.backblazeb2.com/file/thijsp-blog"
absbucketurl: ""

# apiurl: "https://website-api-thijsp.replit.app"
apiurl: "https://api.thijspeirelinck.be"
# apiurl: "https://websiteapi.thijsp.repl.co"
# apiurl: http://127.0.0.1:5000
# apiurl: "https://74ebf454-28f5-41d6-8891-2e1af4799081-00-2ncs2a95zju20.picard.replit.dev:3000/"

# default page image
image: "/main.jpeg"

# categories used to provide filters at the top of hiking page
hikingfilters: ["Belgium", "Day hike", "Two-day hike", "Multi-day hike"]

# SCSS
sass:
  style: compact

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - netlify.toml


# -------------------
# Theme Config
# --------------------
title: "Thijs Peirelinck"
category_dir: category

colors:
  #light-mode colors
  primary: "#0d042b"
  primary_2: "#0d042b"
  primary_text: "#fdfcf9"
  background: "#fdfcf9"
  background_2: "#f7f6ed"
  background_3: "#faebd7"
  text: "#0d042b"
  text_2: "#3b364c"

  # dark-mode colors
  primary_dark: "#c1c4d4"
  # primary_dark: "#171716"
  primary_2_dark: "#0d042b"
  # primary_2_dark: "#bebfed"
  primary_text_dark: "#fdfcf9"
  # background_dark: "#0b0326"
  background_dark: "#171716"
  # background_2_dark: "#150c32"
  background_2_dark: "#292927"
  background_3_dark: "#251654"
  text_dark: "#f5f5ec"
  text_2_dark: "#929eaf"

fonts:
  google_fonts: "https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Fira+Mono&display=swap"
  heading: "DM Sans"
  base: "DM Sans"
  monospace: "Fira Mono"
  logo: "DM Sans"

# logo:
#   logo_text: "Thijs Peirelinck - Home"
#   logo_image: assets/images/logo/logo.png
#   logo_image_mobile: assets/images/logo/logo-mobile.png
#   logo_image_invert: assets/images/logo/logo-invert.png
#   logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.png
#   logo_image_desktop_height: "28px"
#   logo_image_desktop_width: "28px"
#   logo_image_mobile_height: "28px"
#   logo_image_mobile_width: "28px"
#   show_logo_image_on_mobile: true
#   show_logo_image_on_desktop: true
#   show_logo_text_on_mobile: false
#   show_logo_text_on_desktop: false

logo: assets/images/logo/logo.png
  
  
header: 
  fixed: true
  logo_text: "Thijs Peirelinck - Home"
  header_logo_image: assets/images/logo/logo.png
  header_logo_image_mobile: assets/images/logo/logo-mobile.png
  header_logo_image_invert: assets/images/logo/logo-invert.png
  header_logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.png
  header_logo_image_desktop_height: "28px"
  header_logo_image_desktop_width: "28px"
  header_logo_image_mobile_height: "28px"
  header_logo_image_mobile_width: "28px"
  header_show_logo_image_on_mobile: true
  header_show_logo_image_on_desktop: true
  header_show_logo_text_on_mobile: false
  header_show_logo_text_on_desktop: true

darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: true
  show_dark_mode_toggle_in_bottom: false
  show_dark_mode_toggle_in_mobile_menu: true

analytics:
  google_analytics_id: "G-4JTVX6C0XC"

disqus:
  # shortname: "thijsp-blog" # Your disqus shortcode. leave this blank to disable comments globally

mailchimp:
  form_action_url: https://zerostatic.us13.list-manage.com/subscribe/post?u=675276692aebec1c007f8156d&amp;id=3e3da720c2

contact_form: 
  use_netlify_form: false
  use_formspree_form: false
  formspree_endpoint: https://formspree.io/f/moqyklqv

menu: 
  show_dropdown_items_in_mobile_menu: true
  show_social_media_in_mobile_menu: true

social:
  name: Thijs Peirelinck
  links:
    - https://www.instagram.com/timelapsingthikkes/?hl=en
    - https://www.linkedin.com/in/thijspeirelinck
    - https://photog.social/@thijspeirelinck

footer:
  enable_footer: true # show/hide the entire footer
  footer_title: "Thijs Peirelinck"
  footer_description: "Find me on the following social networks:"
  enable_social_media_icons: true
  enable_contact_details: false
  enable_menu_footer_primary: true
  enable_menu_footer_secondary: true
  enable_menu_footer_tertiary: true
  footer_primary_menu_title: "Photography"
  footer_secondary_menu_title: "Research"
  footer_tertiary_menu_title: "Hikes"

bottom:
  enable_bottom: true # show/hide the entire bottom (below the footer)
  enable_bottom_menu: false # if enabled, the bottom menu can be edited in `_data/menu.yml`
  copyright_text: "© 2025 Thijs Peirelinck"

timezone: "Europe/Brussels"

